//import 'package:couchbase_lite/couchbase_lite.dart';
//import 'package:flutter/cupertino.dart';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'package:flutter_todolist/onboarding.dart';
import 'util.dart';

void main() => runApp(App());

class App extends StatefulWidget {
  App({Key key}) : super(key: key);

  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  //Future<Database> database1;
  //Database database;
  @override
  void initState() {
    SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle(
        statusBarColor: Colors.transparent, //top bar color
      ),
    );
    // SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.top]);
    super.initState();
    //initializeCouchbaseDbAsync();

  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        canvasColor: CustomColors.GreyBackground,
        fontFamily: 'rubik',
      ),
      home: Onboarding(),
    );
  }
/**
  void initializeCouchbaseDbAsync() async {
// Initialize the database
    try {
      database = await Database.initWithName("goAchieveNowMallik");
      //print("Created database" + database.toString());
    } on PlatformException {
      print("Error PlatformException");
    }

// Create a new document (i.e. a record) in the database.
    var mutableDoc = MutableDocument()
        .setDouble("version", 2.0)
        .setString("type", "SDK");

// Save it to the database.
    try{
      await database.saveDocument(mutableDoc);
      print("saveDocument database" + database.toString());
    } on PlatformException {
      print("Error PlatformException");
    }

// Update a document.
    mutableDoc = (await database.document(mutableDoc.id))?.toMutable()?.setString("language", "Dart");

    if (mutableDoc != null) {
      // Save it to the database.
      try {
        await database.saveDocument(mutableDoc);

        var document = await database.document(mutableDoc.id);

        // Log the document ID (generated by the database)
        // and properties
        print("Document ID :: ${document.id}");
        print("Learning ${document.getString("language")}");
      } on PlatformException {
      }
    }

// Create a query to fetch documents of type SDK.
    var query = QueryBuilder
        .select([SelectResult.all().from("mydocs")])
        .from("goAchieveNowMallik", as: "mydocs")
        .where(Expression.property("type").from("mydocs").equalTo(Expression.string("SDK")));

// Run the query.
    try {
      var result = await query.execute();
      print("Number of rows :: ${result.allResults().length}");
    } on PlatformException {
    }
  }

  **/

}
